- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: argocd
    repo: argoproj/argo-cd
    version_check_command: argocd version --client -o json
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and install argocd
  when: current_argocd_version | default('none') != argocd_version
  become: true
  get_url:
    url: https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-{{ arch }}
    dest: /usr/local/bin/argocd
    force: true
    mode: "u=xrw,g=xr,o=x"
