- name: Find latest version of bw
  when: bw_version is not defined
  uri:
    url: https://api.github.com/repos/bitwarden/clients/releases
    return_content: true
  register: releases

- name: Set kustomize version
  when: bw_version is not defined
  set_fact:
    # Bitwarden clients has multiple components which means that they use tags like "cli-vYYYY.M.i", so we have to parse it a bit.
    bw_version: "{{ releases.content | from_json | json_query(query) | first | regex_search('v[0-9]{4}\\.[0-9]+\\.[0-9]+') }}"
  vars:
    query: "[?starts_with(tag_name, 'cli')].tag_name"

- name: Check current bw version
  command: bw --version
  register: bw_output
  ignore_errors: true
  changed_when: False

- name: Set current bw version
  when: bw_output is succeeded
  set_fact:
    current_bw_version: "v{{ bw_output.stdout_lines[0] | regex_search('[0-9]{4}\\.[0-9]+\\.[0-9]+') }}"

- name: Download, extract and install bw
  when: current_bw_version | default('none') != bw_version
  become: true
  unarchive:
    src: "https://github.com/bitwarden/clients/releases/download/cli-{{ bw_version }}/bw-linux-{{ bw_version |replace( 'v', '') }}.zip"
    dest: /usr/local/bin/
    remote_src: true
