- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: bw
    repo: bitwarden/clients
    releases_url_suffix: "" # Get all releases instead of latest
    tag_filter_query: "[?starts_with(tag_name, 'cli')].tag_name | [0]"
    version_check_command: bw --version
    version_pattern: "v[0-9]{4}\\.[0-9]+\\.[0-9]+"

- name: Download and install bw
  when: current_bw_version | default('none') != bw_version
  become: true
  unarchive:
    src: "https://github.com/bitwarden/clients/releases/download/cli-{{ bw_version }}/bw-linux-{{ bw_version |replace( 'v', '') }}.zip"
    dest: /usr/local/bin/
    remote_src: true
