- name: Install Chrome repository
  dnf:
    name: fedora-workstation-repositories
    state: present

- name: Enable Chrome repository
  command: dnf config-manager --set-enabled google-chrome

- name: Install Chrome
  dnf:
    name: google-chrome-stable
    state: present
