- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: clusterctl
    repo: kubernetes-sigs/cluster-api
    version_check_command: clusterctl version -o short
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and install clusterctl
  when: current_clusterctl_version | default('none') != clusterctl_version
  become: true
  get_url:
    url: https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterctl_version }}/clusterctl-linux-{{ arch }}
    dest: /usr/local/bin/clusterctl
    force: true
    mode: "u=xrw,g=xr,o=x"
