- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: cmctl
    repo: cert-manager/cmctl
    version_check_command: cmctl version --client
    version_pattern: v([0-9]+\.){2}[0-9]+



- name: Download, extract and install cmctl
  when: current_cmctl_version | default('none') != cmctl_version
  become: true
  unarchive:
    src: https://github.com/cert-manager/cmctl/releases/download/{{ cmctl_version }}/cmctl_linux_{{ arch }}.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # The specific file(s) to extract
    - cmctl
