- name: Add Docker apt key.
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ distro }}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/{{ distro }} {{ ansible_distribution_release }} stable"
    state: present
  register: docker_repository

- name: Install docker
  become: true
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    update_cache: "{{ docker_repository is changed | bool }}"

- name: Adding user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
