- name: Add flathub repo if needed
  become: yes
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  ignore_errors: yes

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - io.atom.Atom
      - org.gnome.gitg
      - org.gnome.meld
      - org.gnome.DejaDup
      - org.gnome.Polari
      - org.filezillaproject.Filezilla
      - com.slack.Slack
      - org.videolan.VLC
      - com.getpostman.Postman
      - org.telegram.desktop
      - org.libreoffice.LibreOffice
