- name: Add flathub repo if needed
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  ignore_errors: true

- name: Install flatpaks
  community.general.flatpak:
    name:
    - be.alexandervanhee.gradia
    - com.bitwarden.desktop
    - com.getpostman.Postman
    - com.github.maoschanz.drawing
    - com.github.tchx84.Flatseal
    - com.slack.Slack
    - com.visualstudio.code
    - dev.zed.Zed
    - it.mijorus.gearlever
    - org.filezillaproject.Filezilla
    - org.gnome.gitg
    - org.gnome.meld
    - org.gnome.DejaDup
    - org.gnome.Polari
    - org.mozilla.firefox
    - org.videolan.VLC
    - org.telegram.desktop
    - org.libreoffice.LibreOffice
    - com.github.jeromerobert.pdfarranger

- name: Configure VS Code
  command: "{{ item }}"
  loop:
  - flatpak override --user --filesystem=/run/docker.sock com.visualstudio.code
