- name: Add flathub repo if needed
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  ignore_errors: yes

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
  loop:
      - com.bitwarden.desktop
      - io.atom.Atom
      - org.gnome.gitg
      - org.gnome.meld
      - org.gnome.DejaDup
      - org.gnome.Polari
      - org.filezillaproject.Filezilla
      - com.slack.Slack
      - org.videolan.VLC
      - com.getpostman.Postman
      - org.telegram.desktop
      - org.octave.Octave
      - org.nextcloud.Nextcloud
      - com.valvesoftware.Steam
      - org.texstudio.TeXstudio
      - org.libreoffice.LibreOffice

# TODO: flatpak override com.valvesoftware.Steam --filesystem=/media/Data
