- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: fzf
    repo: junegunn/fzf
    version_check_command: fzf --version
    version_pattern: v([0-9]+\.){2}[0-9]+
    add_v_prefix: true

- name: Download and install fzf
  when: current_fzf_version | default('none') != fzf_version
  become: true
  unarchive:
    # https://github.com/junegunn/fzf/releases/download/v0.65.0/fzf-0.65.0-linux_amd64.tar.gz
    src: "https://github.com/junegunn/fzf/releases/download/{{ fzf_version }}/fzf-{{ fzf_version | replace('v', '') }}-linux_{{ arch }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # The specific file(s) to extract
    - fzf

- name: Add zoxide to bashrc
  blockinfile:
    content: |
      # Set up fzf key bindings and fuzzy completion
      eval "$(fzf --bash)"
    path: /home/{{ ansible_user_id }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK fzf"
