- name: Find latest version of gh
  uri:
    url: https://api.github.com/repos/cli/cli/releases/latest
    return_content: true
  register: latest_release

- name: Set gh version
  when: gh_version is not defined
  set_fact:
    gh_version: "{{ (latest_release.content | from_json).tag_name | regex_replace('^v', '') }}"

- name: Check current gh version
  command: gh --version
  register: gh_output
  ignore_errors: true
  changed_when: False

- name: Set current gh version
  when: gh_output is succeeded
  set_fact:
    current_gh_version: "{{ gh_output.stdout_lines[0] | regex_search('([0-9]+\\.){2}[0-9]+') }}"

- name: Download, extract and install gh
  when: current_gh_version | default('none') != gh_version
  become: true
  unarchive:
    src: "https://github.com/cli/cli/releases/download/v{{ gh_version }}/gh_{{ gh_version }}_linux_amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # Skip the folder
    - --strip=2
    # The specific file(s) to extract
    - gh_{{ gh_version }}_linux_amd64/bin/gh
