- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: gh
    repo: cli/cli
    version_check_command: gh version
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and install gh
  when: current_gh_version | default('none') != gh_version
  become: true
  unarchive:
    src: "https://github.com/cli/cli/releases/download/{{ gh_version }}/gh_{{ gh_version | replace('v', '') }}_linux_{{ arch }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # Skip the folder
    - --strip=2
    # The specific file(s) to extract
    - gh_{{ gh_version | replace('v', '') }}_linux_{{ arch }}/bin/gh
