- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: helm
    repo: helm/helm
    version_check_command: helm version --template "{{'{{'}}.Version{{'}}'}}"

- name: Download and install helm
  when: current_helm_version | default('none') != helm_version
  become: true
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-{{ arch }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # Skip the folder
    - --strip=1
    # The specific file(s) to extract
    - linux-{{ arch }}/helm

- name: Make helm executable
  become: true
  file:
    path: /usr/local/bin/helm
    mode: "u=xrw,g=xr,o=x"
