- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: k9s
    repo: derailed/k9s
    version_check_command: k9s version
    version_pattern: v([0-9]+\.){2}[0-9]+



- name: Download, extract and install k9s
  when: current_k9s_version | default('none') != k9s_version
  become: true
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ arch }}.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # The specific file(s) to extract
    - k9s
