- name: Find latest version of k9s
  uri:
    url: https://api.github.com/repos/derailed/k9s/releases/latest
    return_content: true
  register: latest_release

- name: Set k9s version
  when: k9s_version is not defined
  set_fact:
    k9s_version: "{{ (latest_release.content | from_json).tag_name }}"

- name: Check current k9s version
  command: k9s version --short
  register: k9s_output
  ignore_errors: true
  changed_when: False

- name: Set current k9s version
  when: k9s_output is succeeded
  set_fact:
    current_k9s_version: "{{ k9s_output.stdout_lines[0] | regex_search('v([0-9]+\\.){2}[0-9]+') }}"

- name: Download, extract and install k9s
  when: current_k9s_version | default('none') != k9s_version
  become: true
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ arch }}.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # The specific file(s) to extract
    - k9s
