- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: kind
    repo: kubernetes-sigs/kind
    version_check_command: kind version
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and install kind
  when: current_kind_version | default('none') != kind_version
  become: true
  get_url:
    url: "https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_version }}/kind-linux-{{ arch }}"
    dest: /usr/local/bin/kind
    mode: "u=xrw,g=xr,o=x"
    force: true

# When working with kind and larger clusters with many containers, it is easy to run into
# "too many open files" issues. Increase the limits a bit to avoid this.
- name: Increase inotify watch limits
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "1048576"
- name: Increase inotify instance limits
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "8192"
