- name: Find latest version of kind
  when: kind_version is not defined
  uri:
    url: https://api.github.com/repos/kubernetes-sigs/kind/releases/latest
    return_content: true
  register: latest_release

- name: Set kind version
  when: kind_version is not defined
  set_fact:
    kind_version: "{{ (latest_release.content | from_json).tag_name }}"

- name: Check current kind version
  command: kind version
  register: kind_output
  ignore_errors: true
  changed_when: False

- name: Set current kind version
  when: kind_output is succeeded
  set_fact:
    current_kind_version: "{{ kind_output.stdout_lines[0] | regex_search('v([0-9]+\\.){2}[0-9]+') }}"

- name: Download kind
  when: current_kind_version | default('none') != kind_version
  become: true
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_version }}/kind-linux-{{ arch }}
    dest: /usr/local/bin/kind
    mode: "u=xrw,g=xr,o=x"
    force: true

# When working with kind and larger clusters with many containers, it is easy to run into
# "too many open files" issues. Increase the limits a bit to avoid this.
- name: Increase inotify watch limits
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "1048576"
- name: Increase inotify instance limits
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "8192"
