- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: krew
    repo: kubernetes-sigs/krew
    version_check_command: kubectl krew version
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and extract krew
  when: current_krew_version | default('none') != krew_version
  unarchive:
    src: "https://github.com/kubernetes-sigs/krew/releases/download/{{ krew_version }}/krew-linux_amd64.tar.gz"
    dest: /tmp
    remote_src: true
    extra_opts:
    # Skip the folder
    - --strip=1
    # The specific file(s) to extract
    - ./krew-linux_amd64

- name: Install krew
  when: current_krew_version | default('none') != krew_version
  ansible.builtin.command: /tmp/krew-linux_amd64 install krew

- name: Add krew bin to path
  become: false
  blockinfile:
    content: |
      # Krew
      export PATH="${KREW_ROOT:-${HOME}/.krew}/bin:$PATH"
    path: "{{ ansible_user_dir }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK KREW"
