- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: kubebuilder
    repo: kubernetes-sigs/kubebuilder
    version_check_command: kubebuilder version
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download kubebuilder
  when: current_kubebuilder_version | default('none') != kubebuilder_version
  become: true
  get_url:
    url: https://github.com/kubernetes-sigs/kubebuilder/releases/download/{{ kubebuilder_version }}/kubebuilder_linux_{{ arch }}
    dest: /usr/local/bin/kubebuilder
    mode: "u=xrw,g=xr,o=x"
    force: true
