- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: kustomize
    repo: kubernetes-sigs/kustomize
    releases_url_suffix: "" # Get all releases, not just latest
    tag_filter_query: "[?starts_with(tag_name, 'kustomize')].tag_name | [0]"
    version_check_command: kustomize version
    version_pattern: "v([0-9]+\\.){2}[0-9]+"

- name: Download and install kustomize
  when: current_kustomize_version | default('none') != kustomize_version
  become: true
  unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_{{ arch }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
