- name: Find latest version of kwok
  when: kwok_version is not defined
  uri:
    url: https://api.github.com/repos/kubernetes-sigs/kwok/releases/latest
    return_content: true
  register: latest_release

- name: Set kwok version
  when: kwok_version is not defined
  set_fact:
    kwok_version: "{{ (latest_release.content | from_json).tag_name }}"

- name: Check current kwok version
  command: kwok --version
  register: kwok_output
  ignore_errors: true
  changed_when: False

- name: Set current kwok version
  when: kwok_output is succeeded
  set_fact:
    current_kwok_version: "{{ kwok_output.stdout_lines[0] | regex_search('v([0-9]+\\.){2}[0-9]+') }}"

- name: Download kwok
  when: current_kwok_version | default('none') != kwok_version
  become: true
  get_url:
    url: https://github.com/kubernetes-sigs/kwok/releases/download/{{ kwok_version }}/kwok-linux-{{ arch }}
    dest: /usr/local/bin/kwok
    mode: "u=xrw,g=xr,o=x"
    force: true

- name: Download kwokctl
  when: current_kwok_version | default('none') != kwok_version
  become: true
  get_url:
    url: https://github.com/kubernetes-sigs/kwok/releases/download/{{ kwok_version }}/kwokctl-linux-{{ arch }}
    dest: /usr/local/bin/kwokctl
    mode: "u=xrw,g=xr,o=x"
    force: true
