- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: kwok
    repo: kubernetes-sigs/kwok
    version_check_command: kwok --version
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and install kwok
  when: current_kwok_version | default('none') != kwok_version
  become: true
  get_url:
    url: "https://github.com/kubernetes-sigs/kwok/releases/download/{{ kwok_version }}/kwok-linux-{{ arch }}"
    dest: /usr/local/bin/kwok
    mode: "u=xrw,g=xr,o=x"
    force: true
