- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: minikube
    repo: kubernetes/minikube
    version_check_command: minikube version --short
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and install minikube
  when: current_minikube_version | default('none') != minikube_version
  become: true
  get_url:
    url: "https://github.com/kubernetes/minikube/releases/download/{{ minikube_version }}/minikube-linux-{{ arch }}"
    dest: /usr/local/bin/minikube
    mode: "u=xrw,g=xr,o=x"
    force: true
