- name: Ensure user@.service.d systemd folder
  file:
    path: /etc/systemd/system/user@.service.d
    state: directory

- name: Delegate CPU controller
  copy:
    src: delegate.conf
    dest: /etc/systemd/system/user@.service.d/delegate.conf

- name: Ensure iptables kernel modules are loaded
  copy:
    src: iptables.conf
    dest: /etc/modules-load.d/iptables.conf

- name: Daemon reload
  systemd:
    daemon_reload: true
