---
- name: Find latest version of sops
  uri:
    url: https://api.github.com/repos/mozilla/sops/releases/latest
    return_content: yes
  register: latest_release

- name: Get sops latest tag name
  set_fact:
    sops_tag: "{{ (latest_release.content | from_json).tag_name }}"

- name: Download and install sops
  become: yes
  get_url:
    url: "https://github.com/mozilla/sops/releases/download/{{ sops_tag }}/sops-{{ sops_tag }}.linux"
    dest: /usr/local/bin/sops
    mode: "u=xrw,g=xr,o=x"
    force: yes
