- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: sopssecretgenerator
    repo: goabout/kustomize-sopssecretgenerator
    # There is no version command. This is just a placeholder to check the version.
    version_check_command: sopssecretgenerator version
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Ensure sopssecretgenerator directory exists
  when: current_sopssecretgenerator_version | default('none') != sopssecretgenerator_version
  file:
    path: /home/{{ ansible_user_id }}/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator
    state: directory
    mode: "u=xrw,g=xr,o=x"

- name: Download and install sopssecretgenerator
  when: current_sopssecretgenerator_version | default('none') != sopssecretgenerator_version
  become: true
  get_url:
    url: https://github.com/goabout/kustomize-sopssecretgenerator/releases/download/{{ sopssecretgenerator_version }}/SopsSecretGenerator_{{ sopssecretgenerator_version | replace("v", "") }}_linux_{{ arch }}
    dest: /home/{{ ansible_user_id }}/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator
    mode: "u=xrw,g=xr,o=x"
    force: true
