- name: Find latest version of SopsSecretGenerator
  when: kss_version is not defined
  uri:
    url: https://api.github.com/repos/goabout/kustomize-sopssecretgenerator/releases/latest
    return_content: true
  register: latest_release

- name: Set SopsSecretGenerator version
  when: kss_version is not defined
  set_fact:
    kss_version: "{{ (latest_release.content | from_json).tag_name }}"

# TODO: There is no way to get the version currently.
# - name: Check current kss version
#   command: kss version
#   register: kss_output
#   ignore_errors: true
#   changed_when: False
#
# - name: Set current SopsSecretGenerator version
#   when: kss_output is succeeded
#   set_fact:
#     current_kss_version: "{{ kss_output.stdout_lines[0] | regex_search('v([0-9]+\\.){2}[0-9]+') }}"

- name: Create folder for SopsSecretGenerator
  file:
    path: "/home/{{ ansible_user_id }}/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"


- name: Download SopsSecretGenerator
  when: current_kss_version | default('none') != kss_version
  get_url:
    url: https://github.com/goabout/kustomize-sopssecretgenerator/releases/download/{{ kss_version }}/SopsSecretGenerator_{{ kss_version | replace("v", "") }}_linux_amd64
    dest: /home/{{ ansible_user_id }}/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator
    mode: "u=xrw,g=xr,o=x"
    force: true
