- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: sops
    repo: getsops/sops
    version_check_command: sops --version
    version_pattern: ([0-9]+\.){2}[0-9]+

- name: Download and install sops
  when: current_sops_version | default('none') != sops_version
  become: true
  get_url:
    url: "https://github.com/getsops/sops/releases/download/{{ sops_version }}/sops-{{ sops_version }}.linux.{{ arch }}"
    dest: /usr/local/bin/sops
    mode: "u=xrw,g=xr,o=x"
    force: true
