- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: starship
    repo: starship/starship
    version_check_command: starship --version
    version_pattern: v([0-9]+\.){2}[0-9]+

- name: Download and install starship
  when: current_starship_version | default('none') != starship_version
  become: true
  unarchive:
    src: "https://github.com/starship/starship/releases/download/{{ starship_version }}/starship-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    dest: /usr/local/bin/
    remote_src: true

- name: Add starship to bashrc
  blockinfile:
    content: |
      # Starship
      if command -v starship > /dev/null; then
          eval "$(starship init bash)"
      fi
    path: /home/{{ ansible_user_id }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK STARSHIP"

- name: Add starship config
  copy:
    src: starship.toml
    dest: /home/{{ ansible_user_id }}/.config/starship.toml
