- name: Set facts
  ansible.builtin.set_fact:
    distro: "{{ ansible_facts['distribution'] | lower }}"
    arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }}"
