- name: Update apt cache
  become: true
  when: ansible_facts["distribution"] == 'Ubuntu' or ansible_facts["distribution"] == 'Debian'
  apt:
    update_cache: yes

- name: Install base packages
  become: true
  when: ansible_facts["distribution"] == 'Ubuntu' or ansible_facts["distribution"] == 'Debian'
  package:
    name:
    - git
    - htop
    - unzip
    - vim
    - hunspell-sv
    - logrotate
    - nfs-common
    - wget
    - tar
    - byobu
    - scdaemon
    - pcscd
    - libssl-dev
    - swig
    - libpcsclite-dev

- name: Install base packages
  become: true
  # Silverblue
  when: ansible_facts["pkg_mgr"] == 'atomic_container'
  community.general.rpm_ostree_pkg:
    name:
    - byobu

- name: Check available editor
  file:
    path: /usr/bin/vim
  register: vim_file
  failed_when: false
  tags: ["editor"]

- name: Set default editor to vim
  blockinfile:
    content: |
      export EDITOR="/usr/bin/{{ 'vim' if vim_file.state == 'file' else 'vi' }}"
    path: "{{ ansible_facts['user_dir'] }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK EDITOR"
  tags: ["editor"]
