- name: Install base packages
  become: yes
  when: ansible_distribution == 'Fedora' and ansible_pkg_mgr != 'atomic_container'
  dnf:
    name:
      - python3-libselinux
      - git
      - htop
      - screenfetch
      - unzip
      - vim-enhanced
      - hunspell-sv
      - langpacks-sv
      - langpacks-en
      - logrotate
      - nfs-utils
      - wget
      - tar
      - byobu

- name: Install base packages
  become: yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name:
      - git
      - htop
      - screenfetch
      - unzip
      - vim
      - hunspell-sv
      - logrotate
      - nfs-common
      - wget
      - tar
      - byobu
      - scdaemon
      - pcscd
      - libssl-dev
      - swig
      - libpcsclite-dev

- name: Install base packages
  become: yes
  # Silverblue
  when: ansible_pkg_mgr == 'atomic_container'
  community.general.rpm_ostree_pkg:
    name:
      - byobu
      - arm-image-installer

- name: Set default editor to vim
  blockinfile:
    content: |
      export EDITOR="/usr/bin/vim"
    path: /home/{{ ansible_user_id }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK EDITOR"
  tags: ["editor"]

- name: Copy public PGP key
  copy:
    src: PGP-public-key.txt
    dest: /home/{{ ansible_user_id }}/PGP-public-key.txt

- name: Import PGP public key
  command: gpg --import /home/{{ ansible_user_id }}/PGP-public-key.txt

# TODO: check value first instead of just overwriting every time
- name: Set name for git
  command: git config --global user.name "Lennart Jern"
# TODO: Prompt for email and key to use?
# - name: Set signing key for git
#   command: git config --global user.signingKey 3820F67B590431A8E2ECBBC88CC3ECACCE12D523

# TODO:
# - Restart pcscd?
# - Configure scdaemon.conf "reader-port Yubico Yubi"?
# - Configure git email?
