- name: Install base packages
  become: true
  when: ansible_distribution == 'Fedora' and ansible_pkg_mgr != 'atomic_container'
  dnf:
    name:
    - python3-libselinux
    - git
    - htop
    - screenfetch
    - unzip
    - vim-enhanced
    - hunspell-sv
    - langpacks-sv
    - langpacks-en
    - logrotate
    - nfs-utils
    - wget
    - tar
    - byobu

- name: Install base packages
  become: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  package:
    name:
    - git
    - htop
    - screenfetch
    - unzip
    - vim
    - hunspell-sv
    - logrotate
    - nfs-common
    - wget
    - tar
    - byobu
    - scdaemon
    - pcscd
    - libssl-dev
    - swig
    - libpcsclite-dev

- name: Install base packages
  become: true
  # Silverblue
  when: ansible_pkg_mgr == 'atomic_container'
  community.general.rpm_ostree_pkg:
    name:
    - byobu

- name: Check available editor
  file:
    path: /usr/bin/vim
  register: vim_file
  failed_when: false
  tags: ["editor"]

- name: Set default editor to vim
  blockinfile:
    content: |
      export EDITOR="/usr/bin/{{ 'vim' if vim_file.state == 'file' else 'vi' }}"
    path: "{{ ansible_user_dir }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK EDITOR"
  tags: ["editor"]
